### PR TITLE
Refactor jms implementation

### PR DESCRIPTION
**Pull request by neomatrix369**
Actually syncing master with this branch after checking out v0.24 of tdl-client-spec

### CODE REVIEW

**Comment by neomatrix369** [comment]
Strange issue in the build.gradle file https://app.codeship.com/projects/90604/builds/37758082?pipeline=c2bf4c7f-711e-42dd-b7be-b784e58944a3 (line 67):
```groovy
def majorMinorVersion = '0.0'
if (git_describe_process.exitValue() == 0 ) {
    majorMinorVersion = sout.toString().split('v')[1] <=== line 67
} else {
    logger.warn('Failed to retrieve Spec version from git describe. Setting version to 0.0')
}

```

causing the build to fail

And I didn't change anything in the gradle project file or any gradle related files

**Comment by neomatrix369** [comment]
I had a look at the steps CodeShip takes and replicated all of them and here's the snippet of the step that fails on CodeShip but works fine on my local machine (ran in the temp dir and even deleted all distributions of Gradle):

```gradle
[snipped]
./gradlew test -i                    
Downloading http://services.gradle.org/distributions/gradle-4.0-all.zip
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/satyasai/.gradle/wrapper/dists/gradle-4.0-all/bgamk96uxwdunkspgx62gq17x/gradle-4.0-all.zip to /home/satyasai/.gradle/wrapper/dists/gradle-4.0-all/bgamk96uxwdunkspgx62gq17x
Set executable permissions for: /home/satyasai/.gradle/wrapper/dists/gradle-4.0-all/bgamk96uxwdunkspgx62gq17x/gradle-4.0/bin/gradle
Initialized native services in: /home/satyasai/.gradle/native
The client will now receive all logging from the daemon (pid: 10975). The daemon log file: /home/satyasai/.gradle/daemon/4.0/daemon-10975.out.log
Starting 2nd build in daemon [uptime: 2 mins 47.124 secs, performance: 100%, no major garbage collections]
Using 8 worker leases.
Creating new cache for fileHashes, path /tmp/tdl-client-java/.gradle/4.0/fileHashes/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@7d3c1f67
Creating new cache for plugin-use-metadata, path /home/satyasai/.gradle/caches/4.0/plugin-resolution/plugin-use-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@57807e76
Creating new cache for client-status, path /home/satyasai/.gradle/caches/4.0/plugin-resolution/client-status.bin, access org.gradle.cache.internal.DefaultCacheAccess@57807e76
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/tmp/tdl-client-java/build.gradle'.
Included projects: [root project 'tdl-client-java']

> Configure project :
Evaluating root project 'tdl-client-java' using build file '/tmp/tdl-client-java/build.gradle'.
Creating new cache for metadata-1.1/results, path /home/satyasai/.gradle/caches/transforms-1/metadata-1.1/results.bin, access org.gradle.cache.internal.DefaultCacheAccess@70c18e15

All projects evaluated.
Selected primary task 'test' from project :
Creating new cache for annotation-processors, path /tmp/tdl-client-java/.gradle/4.0/fileContent/annotation-processors.bin, access org.gradle.cache.internal.DefaultCacheAccess@55e7cf3d
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':test']
Found class org.gradle.caching.local.internal.DirectoryBuildCacheServiceFactory registered for class org.gradle.caching.local.DirectoryBuildCache
Creating new cache for resourceHashesCache, path /tmp/tdl-client-java/.gradle/4.0/fileHashes/resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@7d3c1f67
Creating new cache for fileSnapshots, path /tmp/tdl-client-java/.gradle/4.0/taskHistory/fileSnapshots.bin, access org.gradle.cache.internal.DefaultCacheAccess@64a97537
Creating new cache for taskHistory, path /tmp/tdl-client-java/.gradle/4.0/taskHistory/taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@64a97537
:compileJava (Thread[Task worker,5,main]) started.

> Task :compileJava
Putting task artifact state for task ':compileJava' into context took 0.001 secs.
Creating new cache for metadata-2.23/module-metadata, path /home/satyasai/.gradle/caches/modules-2/metadata-2.23/module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@77e47884
Creating new cache for metadata-2.23/artifact-at-repository, path /home/satyasai/.gradle/caches/modules-2/metadata-2.23/artifact-at-repository.bin, access org.gradle.cache.internal.DefaultCacheAccess@77e47884
Skipping task ':compileJava' as it is up-to-date (took 0.043 secs).

:compileJava (Thread[Task worker,5,main]) completed. Took 0.047 secs.
:processResources (Thread[Task worker,5,main]) started.

> Task :processResources
Putting task artifact state for task ':processResources' into context took 0.0 secs.
file or directory '/tmp/tdl-client-java/src/main/resources', not found
Skipping task ':processResources' as it has no source files and no previous output files.

:processResources (Thread[Task worker,5,main]) completed. Took 0.001 secs.
:classes (Thread[Task worker,5,main]) started.

> Task :classes
Skipping task ':classes' as it has no actions.

:classes (Thread[Task worker,5,main]) completed. Took 0.0 secs.
:compileTestJava (Thread[Task worker,5,main]) started.

> Task :compileTestJava
Putting task artifact state for task ':compileTestJava' into context took 0.0 secs.
Creating new cache for metadata-2.23/module-versions, path /home/satyasai/.gradle/caches/modules-2/metadata-2.23/module-versions.bin, access org.gradle.cache.internal.DefaultCacheAccess@77e47884
Creating new cache for metadata-2.23/module-artifacts, path /home/satyasai/.gradle/caches/modules-2/metadata-2.23/module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@77e47884
Skipping task ':compileTestJava' as it is up-to-date (took 0.029 secs).

:compileTestJava (Thread[Task worker,5,main]) completed. Took 0.03 secs.
:processTestResources (Thread[Task worker,5,main]) started.

> Task :processTestResources
Putting task artifact state for task ':processTestResources' into context took 0.0 secs.
Skipping task ':processTestResources' as it is up-to-date (took 0.001 secs).

:processTestResources (Thread[Task worker,5,main]) completed. Took 0.003 secs.
:testClasses (Thread[Task worker,5,main]) started.

> Task :testClasses
Skipping task ':testClasses' as it has no actions.

:testClasses (Thread[Task worker,5,main]) completed. Took 0.0 secs.
:test (Thread[Task worker,5,main]) started.

> Task :test
Putting task artifact state for task ':test' into context took 0.0 secs.
Skipping task ':test' as it is up-to-date (took 0.015 secs).

:test (Thread[Task worker,5,main]) completed. Took 0.017 secs.

BUILD SUCCESSFUL in 1m 32s
4 actionable tasks: 4 up-to-date
Stopped 0 worker daemon(s).
```

**Comment by neomatrix369** [comment]
I think Line 67 might be facing an issue with the format or content of the version string I had a similar issue and patched it temporarily but it is now occurring on CodeShip.

```groovy
    majorMinorVersion = sout.toString().split('v')[1]
```
if `split()` results in an empty error, accessing element 1 might cause a `ArrayIndexOutOfBound`, can we make CodeShip run commands with verbose logging so the below would help:

```
./gradlew test ---debug 
```

I also see a reference to settings.gradle but we dont have one in our project.

```gradle
> IDLE<-------------> 0% INITIALIZING [0s]> settings<-------------> 0% INITIALIZING [1s]<-------------> 0% INITIALIZING [2s]> IDLEaster/settings.gradle'.
```

**Comment by neomatrix369** [comment]
Okay looks like adding `settings.gradle` to the project helped with fixing the build failure.

Although we have another issue which I have been pointing out for a while, there are exceptions at various points in the test execution yet none of the tests fail:

```cucumber
[snipped]
Given There is a challenge server running on "localhost" port 8222 # RunnerSteps.setupServerWithSetup(String,int)
And journeyId is "aJourneyId"                                      # RunnerSteps.journeyid_is(String)
And the challenge server exposes the following endpoints           # RunnerSteps.configureChallengeServerEndpoint(RunnerSteps$ServerConfig>)
And the challenge server exposes the following endpoints           # RunnerSteps.configureChallengeServerEndpoint(RunnerSteps$ServerConfig>)
And There is a recording server running on "localhost" port 41375  # RunnerSteps.setupRecordingServerWithSetup(String,int)
And the recording server exposes the following endpoints           # RunnerSteps.configureRecordingServerEndpoint(RunnerSteps$ServerConfig>)
19:49:07.502 [Test worker] ERROR tdl.client.runner.ChallengeSession - Client threw an unexpected error. Try again.
tdl.client.runner.ChallengeServerClient$OtherCommunicationException: Could not perform GET request
at tdl.client.runner.ChallengeServerClient.get(ChallengeServerClient.java:49) ~[main/:na]
at tdl.client.runner.ChallengeServerClient.getJourneyProgress(ChallengeServerClient.java:27) ~[main/:na]
at tdl.client.runner.ChallengeSession.runApp(ChallengeSession.java:57) [main/:na]
at tdl.client.runner.ChallengeSession.start(ChallengeSession.java:45) [main/:na]
at acceptance.runner.RunnerSteps.userStartsChallenge(RunnerSteps.java:164) [test/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
at cucumber.runtime.Utils$1.call(Utils.java:37) [cucumber-core-1.2.4.jar:na]
at cucumber.runtime.Timeout.timeout(Timeout.java:13) [cucumber-core-1.2.4.jar:na]
```

https://app.codeship.com/projects/90604/builds/37775177?pipeline=b043c428-267c-4f63-82d2-95d9cf726a48

**Review by julianghionoiu — APPROVED** [review]

**Comment by julianghionoiu** [comment]
> Although we have another issue which I have been pointing out for a while, there are exceptions at various points in the test execution yet none of the tests fail:

By the looks of it, the various tests are executed in parallel and that exception actually belongs to a different test, a negative one.

**Pull request merged**
